export * from "./components/AboutExperience";
export * from "./components/AboutHeading";
export * from "./components/AboutHero";
export * from "./components/AboutManifesto";
export * from "./components/AboutPainSolution";
export * from "./components/FitModel";
export * from "./components/AboutAtelier";
export * from "./components/AboutCta";
export * from "./types/about.types";
